/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./static/**/*.{html,js}", "./index.html"],
  theme: {
    extend: {
      colors: {
          "secondary": "#b1c6f9",
          "tertiary-container": "#df7412",
          "on-surface-variant": "#c2c6d6",
          "on-tertiary-container": "#461f00",
          "surface-container-high": "#262a31",
          "primary-fixed-dim": "#adc6ff",
          "on-primary-container": "#00285d",
          "surface-container-lowest": "#0a0e14",
          "on-error": "#690005",
          "tertiary-fixed": "#ffdcc6",
          "surface-bright": "#353940",
          "on-primary-fixed": "#001a42",
          "secondary-fixed": "#d8e2ff",
          "on-secondary": "#182f59",
          "on-tertiary": "#502400",
          "on-tertiary-fixed": "#311400",
          "error": "#ffb4ab",
          "primary": "#adc6ff",
          "on-secondary-fixed": "#001a42",
          "surface-container-low": "#181c22",
          "outline-variant": "#424754",
          "inverse-primary": "#005ac2",
          "surface-variant": "#31353c",
          "surface-container": "#1c2026",
          "secondary-fixed-dim": "#b1c6f9",
          "on-tertiary-fixed-variant": "#723600",
          "inverse-on-surface": "#2d3137",
          "on-primary-fixed-variant": "#004395",
          "on-surface": "#dfe2eb",
          "inverse-surface": "#dfe2eb",
          "primary-container": "#4d8eff",
          "surface": "#10141a",
          "surface-tint": "#adc6ff",
          "error-container": "#93000a",
          "tertiary-fixed-dim": "#ffb786",
          "background": "#10141a",
          "secondary-container": "#304671",
          "on-primary": "#002e6a",
          "surface-container-highest": "#31353c",
          "primary-fixed": "#d8e2ff",
          "on-secondary-container": "#9fb5e7",
          "outline": "#8c909f",
          "tertiary": "#ffb786",
          "on-background": "#dfe2eb",
          "surface-dim": "#10141a",
          "on-error-container": "#ffdad6",
          "on-secondary-fixed-variant": "#304671",
          "accent": "#4da6ff"
      },
      fontFamily: {
          "headline": ["Inter", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Space Grotesk", "sans-serif"],
          "mono": ["JetBrains Mono", "monospace"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
